# Generated by Django 5.0.6 on 2026-05-17 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kateqoriya adı')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('title', models.CharField(max_length=200, verbose_name='Vəzifə/Başlıq')),
                ('bio', models.TextField(verbose_name='Haqqında')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profil şəkli')),
                ('cv', models.FileField(blank=True, null=True, upload_to='profile/cv/', verbose_name='CV (PDF)')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='Təcrübə (il)')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Açıqlama')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Qısa açıqlama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/images/', verbose_name='Şəkil')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL (YouTube/Vimeo)')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='projects/videos/', verbose_name='Video fayl')),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='Proyekt URL')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('technologies', models.CharField(blank=True, max_length=500, verbose_name='Texnologiyalar (vergüllə ayırın)')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('completed', 'Tamamlandı'), ('in_progress', 'Davam edir')], default='completed', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Önə çıxarılsın?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra nömrəsi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.category', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Proyekt',
                'verbose_name_plural': 'Proyektlər',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
