# Generated by Django 5.0.6 on 2026-05-17 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Şəkil')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Şəkil açıqlaması')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Proyekt')),
            ],
            options={
                'verbose_name': 'Proyekt Şəkli',
                'verbose_name_plural': 'Proyekt Şəkilləri',
                'ordering': ['order'],
            },
        ),
    ]
