services:
  - type: web
    name: portfolio-backend
    env: python

    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput --clear &&
      python manage.py migrate &&
      python create_superuser.py

    startCommand: gunicorn portfolio_backend.wsgi:application

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString

      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: false

      - key: ALLOWED_HOSTS
        value: .onrender.com

      - key: DJANGO_SUPERUSER_USERNAME
        value: laman.bashirova

      - key: DJANGO_SUPERUSER_EMAIL
        value: lamanmirizada@gmail.com

      - key: DJANGO_SUPERUSER_PASSWORD
        value: David.2025!

databases:
  - name: portfolio-db
    plan: free
